### ISSUE TITLE
Number of results

### ISSUE THREAD

**Issue by SylEleuth** [smartpde/telescope-recent-files#10]
Is it possible to display more results? In my case it varies but it's usually around 50 (46 at the moment). I often go through a lot of files and those that are important quickly disappear from the list.

**Comment by defr0std** [comment]
This plugin does not limit the number of results. Also cannot find if Telescope itself has such setting somewhere.

One thing that could influence the number of results is the size of the shada file. When you close neovim, it writes a fixed number of recent files there, and only these files are available in the picker after the restart. You can increase the number of recent files by doing something like `set shada='200`, see `:h shada` for more detail.

**Comment by SylEleuth** [comment]
Thank You kindly. I will check it out.
