### ISSUE TITLE
Showing the current file, but as the second option

### ISSUE THREAD

**Issue by AntonC9018** [smartpde/telescope-recent-files#13]
I want the previously opened file to be selected when using the picker, but the currently opened file to still be available in the menu (as the first, unselected option).

So like this:
```
third_file
> second_file
current_file
```

I imagine I could easily do it if I had the access to the picker in the handler. So I think it would be a good idea to return the created picker in `pick`. There might be a way to access the global state for the currently active picker with one of telescope API's, but it's not easily discoverable, I couldn't figure it out quickly. And, you know, messing with global state is not great.

**Comment by AntonC9018** [comment]
I've tried doing it, and it's not completely trivial. I mean, I did return the picker, but it doesn't seem to respond to me calling methods on it. Also, we only need to move the selection if there's a file open, which has to be detected somehow, which further complicates the task

**Comment by defr0std** [comment]
Sorry for late reply. But I think I figured out how to do this. 

There is an `on_complete` callback in the picker options. Inside this callback you can perform any action on the picker. Here is an example of how to move the selected item up when the picker is shown:

```lua
require('telescope').extensions.recent_files.pick({
  -- Note that on_complete is the array of callbacks
  on_complete = {
    function(picker)
      require("telescope.actions").move_selection_previous(picker.prompt_bufnr)
    end
  }
})
```
