### ISSUE TITLE
feature request: ignore duplicate files, only show unique

### ISSUE THREAD

**Issue by fent** [smartpde/telescope-recent-files#14]
Hi, thank you for the plugin. I'm using `transform_file_path` in such a way that some files end up being duplicates of one another.

It would be nice to have an option like `ignore_duplicates` or `show_unique_only` to remedy this

**Comment by defr0std** [comment]
Hi,

Thanks for the feedback.  It's strange though, I am using the `transform_file_path` in exactly the same (which could result in duplicates), and I haven't seen this issue. Even if I do this:

```lua
      transform_file_path = function(file)
        return "test.txt"
      end,
```

The picker shows `test.txt` just once.

Maybe the duplicates are showing because of something else?

**Comment by fent** [comment]
Hmm, now that I test it again after clearing my `vim.v.oldfiles`, I can't reproduce it. Also, I have a `path_display` set for telescope, I might have had a path that was different but displaying the same.
