### ISSUE TITLE
buffers opened before plugin is first used are not recorded

### ISSUE THREAD

**Issue by fent** [smartpde/telescope-recent-files#15]
To reproduce
* open a new neovim session
* open a file that you know is not in your recent files history
* `:bdelete` in case your options for recent-files don't show the current file
* show the recent-files list
* you'll see that the file you just opened doesn't show up. if you restart neovim, it does show up since recent-files uses `vim.v.oldfiles`

I suspect this happens because telescope lazy loads plugins, and only loading and setting up plugins when they are first used. The proposal fix I have is, since the plugin still gets loaded into the `rtp`, at least using lazy.nvim, we can run the following in `after`

```lua
require("telescope._extensions.recent_files.recent_files_picker")
```
this will load the autocmd that records files. But it also uses the `options` so maybe remove the [part](https://github.com/smartpde/telescope-recent-files/blob/main/lua/telescope/_extensions/recent_files/recent_files_picker.lua#L38) that transforms the file, and rely on doing so [later](https://github.com/smartpde/telescope-recent-files/blob/main/lua/telescope/_extensions/recent_files/recent_files_picker.lua#L78-L80)

**Comment by defr0std** [comment]
Thanks for the good finding. I will look into this lazy loading a bit later this week.

**Comment by defr0std** [comment]
Sorry for late reply, but I can't reproduce this issue. 

Even if I load the telescope itself using a lazy event, like ` {"nvim-telescope/telescope.nvim", event = "InsertEnter"},` the autocommand in this plugin gets loaded... Could you please share relevant parts of your config?

**Comment by fent** [comment]
I was able to reproduce it using this minimal setup with lazy.nvim

```lua
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  -- add any other plugins here
  {
    "nvim-telescope/telescope.nvim",
    dependencies = {
      "nvim-lua/plenary.nvim",
      "smartpde/telescope-recent-files",
    },
    opts = {},
    keys = {
      {
        "<C-p>",
        "<cmd>lua require('telescope.builtin').find_files()<cr>",
        desc = "Search for files in current directory",
      },
      -- Recent files
      {
        "<leader>r",
        "<cmd>lua require('telescope').extensions.recent_files.pick()<cr>",
        desc = "Search for recently opened files",
      },
    }
  },
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})
```
Save the above file into a temporary directory. Run it with `nvim -u /path/to/above/file.lua`

To reproduce, follow the steps above. Make sure that you open a file that you know is not in your recent files history already. You can check by running recent-files first to see what's in there, but make sure to close and re-open nvim if you do this since the bug happens before recent-files is first loaded.

And make sure you open the file without using recent-files, you can use either telescope's find_files or the `:edit` command.

**Comment by defr0std** [comment]
Thanks for the repro!

So yes, without an explicit call to `load_extension`, it's getting lazy loaded and therefore the autocommands do not get registered. The whole telescope plugin is loaded only on the key mappings.

I can think of several solutions:
1. Explicitly load the extension in the very end of the config file:

```lua
-- Eagerly load the extension.
require("telescope").load_extension("recent_files")
```
This is not very elegant though, since it's detached from the rest of the config.

2. Add `lazy = false`, and a `config` function for the telescope plugin to load the extension:

```lua
{
    "nvim-telescope/telescope.nvim",
    dependencies = {
      "nvim-lua/plenary.nvim",
      "smartpde/telescope-recent-files",
    },
    opts = {},
    keys = {
      {
        "<C-p>",
        "<cmd>lua require('telescope.builtin').find_files()<cr>",
        desc = "Search for files in current directory",
      },
      -- Recent files
      {
        "<leader>r",
        "<cmd>lua require('telescope').extensions.recent_files.pick()<cr>",
        desc = "Search for recently opened files",
      },
    },
    -- Eagerly load telescope to load its extensions
    lazy = false,
    config = function()
        require("telescope").load_extension("recent_files")
    end,
  }
```

3. Variation of the previous option, but instead of `lazy = false`, use a desired event such as `event = "BufEnter"`.

Not sure if anything else is feasible in principle, since this extension does need to be loaded before buffers start getting loaded.
It's worth clarifying this in the documentation.

**Comment by fent** [comment]
Ah, calling `load_extension` does fix this, and it's in the readme. My mistake, thanks!
