### ISSUE TITLE
[BUG] The cwd_only option doesn't work as expected

### ISSUE THREAD

**Issue by dangkhoipro** [smartpde/telescope-recent-files#17]
To reproduce:
- Add cwd_only = true to the setup function
- Open file a.lua inside folder c:/sample/a
- Open file b.lua inside folder c:/sample/a-b
- Open file picker inside folder c:/sample/a

Expected: file b.lua doesn't show up in side picker result
Actual: file b.lua does show up

**Comment by dangkhoipro** [comment]
The reason is that the code compares string `vim.fn.matchstrpos(file_path, cwd)[2] ~= -1` inside function `is_in_cwd` only compare the first path, not immediately followed by an empty string (same folder) or "/" (child folder)
Here is the pull request for this fix https://github.com/smartpde/telescope-recent-files/pull/18

**Comment by defr0std** [comment]
Thanks for the fix! Merged.
