### ISSUE TITLE
Show current file 

### ISSUE THREAD

**Issue by petobens** [smartpde/telescope-recent-files#6]
Hi I read #2 however I was wondering whether it's possible to add an option to display the current file in the picker. The rationale behind this is that even though I know I can use `:Telescope buffers` to show such file I tend to use the recent_files picker. Thanks in advance

**Comment by defr0std** [comment]
Sure, an option for this could be arranged.

**Comment by defr0std** [comment]
Added `show_current_file` option.

```lua
require("telescope").setup {
  -- ...
  extensions = {
    recent_files = {
      show_current_file = true,
    }
  }
}

```

**Comment by petobens** [comment]
Thank you!
