### ISSUE TITLE
path_display not honored

### ISSUE THREAD

**Issue by petobens** [smartpde/telescope-recent-files#7]
Hi! Say I want to replace my home dir (`/home/pedro`) with `~/`. I tried (using pathlib) the following:
```lua
        recent_files = {
            path_display = function(_, path)
                local p = Path:new(path)
                return p.normalize(p)
            end,
        },
```
i.e give a `path_display` config value to my recent_files extension which didn't work. Can this be achieved? Thanks in advance!

**Comment by defr0std** [comment]
Typically, path_display is specified in the main telescope config, not in the extension. Would it work for you?

```lua
require("telescope").setup {
  defaults = {
    path_display = function(opts, path)
        local p = Path:new(path)
        return p.normalize(p)
    end,
  },
  extensions = {
    recent_files = {}
  }
}
require("telescope").load_extension("recent_files")

```

**Comment by petobens** [comment]
I'd rather have it at an extension level. AFAICT that's possible (for instance I pass a path_display option to `live_grep` picker) and it seems to works.

**Comment by defr0std** [comment]
Aha, ok. So you pass the path_display in the picker options to the live_grep call itself, right? E.g. like this:

```
:lua require('telescope.builtin').live_grep({ path_display = "hidden" })
```

Then yes, these picker options should be respected by the recent files picker as well.

**Comment by petobens** [comment]
> Then yes, these picker options should be respected by the recent files picker as well.

However it doesn't seem to be the case: 

```lua
    extensions = {
        fzf = {
            fuzzy = true,
            override_generic_sorter = true,
            override_file_sorter = true,
            case_mode = 'smart_case',
        },
        recent_files = {
            -- FIXME: Not working
            path_display = function(_, path)
                local p = Path:new(path)
                return p.normalize(p)
            end,
        },
```
and I get:

![image](https://user-images.githubusercontent.com/2583971/201200391-425b43d1-30e9-42ce-8577-daf0c72e8ae5.png)

**Comment by petobens** [comment]
Probably a picker option makes more sense yep.

**Comment by defr0std** [comment]
This picker option should work now, for example:

```
:lua require('telescope').extensions.recent_files.pick({ path_display = {shorten=1} })
```

**Comment by petobens** [comment]
Thanks!
